.Dd July 13, 2024
.Os
.Dt tstool 8
.Sh NAME
.Nm tstool
.Nd Timestamping control utility
.Sh SYNOPSIS
.Nm
.Op Fl -help
.Nm
.Op Fl -verbose | v
.Op Fl -config-file Pa file | Fl f Pa file
.Op Fl -persistent
.Op Fl -initial
.Ar command ...
.Sh DESCRIPTION
Examine and adjust PTP Hardware Clock devices, system clock and interface timestamping settings.
.Pp
This utility uses the mechanisms available to sfptpd to manipulate precision clocks on the system.
.Pp
Clocks may be specified by phc number, interface name or 'system'.
.Pp
A configuration file in the same format as used by
.Xr sfptpd 8
may be supplied.
Any settings in the configuration file will take precedence over the command line options.
Note that this behaviour differs from
.Nm sfptpd
which performs a second pass of the command line arguments after interpreting the config file.
The config file is useful for expressing options like
.Ql phc_diff_methods
for defining the preferred clock comparison methods to use.
.Ss Commands
.Bl -item -compact
.It
.Nm clock
list
.It
.Nm clock
info
.Ar clock
.It
.Nm clock
get
.Ar clock
.It
.Nm clock
step
.Ar clock
.Ar offset
.It
.Nm clock
slew
.Ar clock
.Ar ppb
.It
.Nm clock
set_to
.Ar clock1
.Ar clock2
.It
.Nm clock
diff
.Ar clock1
.Ar clock2
.It
.Nm interface
list
.It
.Nm interface
info
.Ar interface
.It
.Nm interface
set_ts
.Ar interface
.Ar tx-type
.Ar rx-filter
.El
.Sh BUGS
Please raise bug reports at:
.Aq https://github.com/Xilinx-CNS/sfptpd/issues
.Pp
Support for users of AMD Solarflare NICs is available from:
.Aq support-nic@amd.com
.Sh AUTHORS
Advanced Micro Devices, Inc.
.Sh SEE ALSO
.Xr sfptpd 8 .
.Pp
Full documentation is available at:
.Aq https://docs.amd.com/r/en-US/ug1602-ptp-user
.Sh COPYRIGHT
Copyright (c) 2024 Advanced Micro Devices, Inc.
