{
 "title": "sfptpd",
 "description": "Example sfptpd Grafana dashboard.\n© Copyright 2025, Advanced Micro Devices, Inc.\nLicense: BSD-3-Clause",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": { "query": "label_values(instance)" } },
   { "name": "SyncInstance", "query": { "query": "label_values(sync)" } }
  ]
 },
 "panels": [
  {
   "title": "In sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "SyncInstance",
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "in_sync{instance=\"$Source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disciplining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "Instances",
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "is_disciplining{instance=\"$Source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "repeat": "SyncInstance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alarms{instance=\"$Source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "repeat": "SyncInstance",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_update_seconds*1000", "legendFormat": "__auto" }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Offset",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "offset_seconds", "legendFormat": "{{instance}}/{{sync}}" }
   ]
  },
  {
   "title": "Frequency adjustment",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppb" } },
   "targets": [
    { "expr": "freq_adj_ratios", "legendFormat": "{{instance}}/{{sync}}" }
   ]
  },
  {
   "title": "P Term (line); I term (filled)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 26 },
   "targets": [
    { "expr": "iterm_ratios", "legendFormat": "{{instance}}/{{sync}}/I" },
    { "expr": "pterm_ratios", "legendFormat": "{{instance}}/{{sync}}/P" }
   ]
  },
  {
   "title": "One way delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "owd_seconds", "legendFormat": "{{instance}}/{{sync}}" }
   ]
  },
  {
   "title": "Alarms",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "alarmtxt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lost RT samples",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lost_rt", "legendFormat": "__auto" }
   ]
  }
 ]
}